version: '3.3'
services:

  postgres:
    image: postgres:10.4
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: ["./cmd.sh"]
    volumes:
      - ./:/usr/src/app
      - django-media:/usr/src/app/media
      - django-static:/usr/src/app/static
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  django-media:
  django-static:
  postgres-data:
